Add kr6 r900-2 support
isys-vision/kuka_experimental pull request #2
Opened 2021-08-24 15:16 UTC by cjue

kr6 r900-2 is identical to kr10 r900-2 except for velocity limits, which were updated from the manual
the kr10 r900-2 meshes are reused

2021-08-24 15:45 UTC, simonschmeisser commented
could you please add the opw parameter file similar to this one https://github.com/isys-vision/kuka_experimental/blob/indigo-devel/kuka_kr4_support/config/opw_parameters_kr4r600.yaml

2021-08-25 13:53 UTC, cjue commented
done

2021-08-25 13:57 UTC, simonschmeisser requested changes
Being a bit pedantic now: could you please also add your model in the package.xml, it contains some hints as to where the data comes from

2021-08-27 14:17 UTC, simonschmeisser requested changes
I added some suggestions that I'll commit now

2021-08-27 14:17 UTC, simonschmeisser commented on kuka_kr6_support/launch/load_kr6r900_2.launch
> +  <param name="robot_description" command="$(find xacro)/xacro.py '$(find kuka_kr6_support)/urdf/kr6r900_2.xacro'"/>
```suggestion
  <param name="robot_description" command="$(find xacro)/xacro '$(find kuka_kr6_support)/urdf/kr6r900_2.xacro'"/>
```

2021-08-27 14:17 UTC, simonschmeisser commented on kuka_kr6_support/urdf/kr6r900_2_macro.xacro
> +      <limit effort="0" lower="${-DEG2RAD * 170}" upper="${DEG2RAD * 170}" velocity="${DEG2RAD * 360}"/>
```suggestion
      <limit effort="0" lower="${radians(-170)}" upper="${radians(170)}" velocity="${radians(360)}"/>
```

2021-08-27 14:17 UTC, simonschmeisser commented on kuka_kr6_support/urdf/kr6r900_2_macro.xacro
> +      <limit effort="0" lower="${-DEG2RAD * 190}" upper="${DEG2RAD * 45}" velocity="${DEG2RAD * 300}"/>
```suggestion
      <limit effort="0" lower="${radians(-190)}" upper="${radians(45)}" velocity="${radians(300)}"/>
```

2021-08-27 14:17 UTC, simonschmeisser commented on kuka_kr6_support/urdf/kr6r900_2_macro.xacro
> +      <limit effort="0" lower="${-DEG2RAD * 120}" upper="${DEG2RAD * 156}" velocity="${DEG2RAD * 360}"/>
```suggestion
      <limit effort="0" lower="${radians(-120)}" upper="${radians(156)}" velocity="${radians(360)}"/>
```

2021-08-27 14:17 UTC, simonschmeisser commented on kuka_kr6_support/urdf/kr6r900_2_macro.xacro
> +      <limit effort="0" lower="${-DEG2RAD * 185}" upper="${DEG2RAD * 185}" velocity="${DEG2RAD * 450}"/>
```suggestion
      <limit effort="0" lower="${radians(-185)}" upper="${radians(185)}" velocity="${radians(450)}"/>
```

2021-08-27 14:17 UTC, simonschmeisser commented on kuka_kr6_support/urdf/kr6r900_2_macro.xacro
> +      <limit effort="0" lower="${-DEG2RAD * 120}" upper="${DEG2RAD * 120}" velocity="${DEG2RAD * 450}"/>
```suggestion
      <limit effort="0" lower="${radians(-120)}" upper="${radians(120)}" velocity="${radians(450)}"/>
```

2021-08-27 14:17 UTC, simonschmeisser commented on kuka_kr6_support/urdf/kr6r900_2_macro.xacro
> +      <limit effort="0" lower="${-DEG2RAD * 350}" upper="${DEG2RAD * 350}" velocity="${DEG2RAD * 540}"/>
```suggestion
      <limit effort="0" lower="${radians(-350)}" upper="${radians(350)}" velocity="${radians(540)}"/>
```

2021-08-27 14:17 UTC, simonschmeisser commented on kuka_kr6_support/urdf/kr6r900_2_macro.xacro
> +      <origin xyz="0 0 0" rpy="0 ${DEG2RAD * 90} 0"/>
```suggestion
      <origin xyz="0 0 0" rpy="0 ${radians(90)} 0"/>
```

2021-08-30 09:35 UTC, merged